[workspace]
members = [
    "core",
    "core/traits",
    "core/host",
    "core/multiaddr",
    "core/peer",
    "protocols",
    "protocols/identify",
    "protocols/floodsub",
    "proto",
    "transport",
    "transport/tcp",
    "transport/udp",
    "muxer/mplex",
    "examples/tcp",
    "examples/ping",
]


resolver = "2"

[workspace.package]
rust-version = "1.90.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rsa = { version = "0.9.8", features = ["sha2"] }
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
unsigned-varint = "0.7"
prost = "0.13"

[workspace.lints]
clippy.pedantic = { level = "allow", priority = -1 }
clippy.unnecessary_wraps = "warn"
