[package]
name = "rnet-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
rnet-multiaddr = {path = "../../core/multiaddr"}
