[package]
name = "rnet-transport-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
async-trait = {workspace = true}
anyhow = {workspace = true}
rnet-core = {path = "../../core"}